# Generated by Django 3.2.7 on 2021-09-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20210908_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='mount',
            new_name='amount',
        ),
    ]
